/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.myproject.dictionary;

import javax.swing.JOptionPane;
/**
 *
 * @author son
 */
public class DictionaryApplication extends javax.swing.JFrame {

    /**
     * Creates new form DictionaryApplication
     */ 
    private DictionaryManagement manage = new DictionaryManagement();
    public DictionaryApplication() {
        initComponents();
        InitDictionary();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        jPopupMenu4 = new javax.swing.JPopupMenu();
        jPopupMenu5 = new javax.swing.JPopupMenu();
        popupMenu1 = new java.awt.PopupMenu();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPopupMenu6 = new javax.swing.JPopupMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        explainT = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        wordList = new javax.swing.JList<>();
        searchT = new javax.swing.JTextField();
        searchB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        engTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vieTextField = new javax.swing.JTextField();
        removeB = new javax.swing.JButton();
        editB = new javax.swing.JButton();
        saveB = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        setResizable(false);

        explainT.setColumns(20);
        explainT.setRows(5);
        jScrollPane1.setViewportView(explainT);

        wordList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(wordList);

        searchT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                searchTInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        searchT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTActionPerformed(evt);
            }
        });
        searchT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchTKeyReleased(evt);
            }
        });

        searchB.setIcon(new javax.swing.ImageIcon("/home/son/NetBeansProjects/Dictionary/images/search-magnifier-interface-symbol.png")); // NOI18N
        searchB.setText("Search");
        searchB.setBorderPainted(false);
        searchB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBMouseClicked(evt);
            }
        });

        addB.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        addB.setIcon(new javax.swing.ImageIcon("/home/son/NetBeansProjects/Dictionary/images/plus.png")); // NOI18N
        addB.setText("Add");
        addB.setBorderPainted(false);
        addB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBMouseClicked(evt);
            }
        });
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });

        jLabel1.setText("English");

        engTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Vietnamese");

        vieTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vieTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPanelLayout = new javax.swing.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(engTextField)
                    .addGroup(addPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 72, Short.MAX_VALUE))
                    .addComponent(vieTextField))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(engTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vieTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        removeB.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        removeB.setIcon(new javax.swing.ImageIcon("/home/son/NetBeansProjects/Dictionary/images/trash-can.png")); // NOI18N
        removeB.setText("Remove");
        removeB.setToolTipText("");
        removeB.setBorderPainted(false);
        removeB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBMouseClicked(evt);
            }
        });

        editB.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 15)); // NOI18N
        editB.setIcon(new javax.swing.ImageIcon("/home/son/NetBeansProjects/Dictionary/images/pencil.png")); // NOI18N
        editB.setText("Edit");
        editB.setBorderPainted(false);
        editB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBMouseClicked(evt);
            }
        });
        editB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBActionPerformed(evt);
            }
        });

        saveB.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 15)); // NOI18N
        saveB.setIcon(new javax.swing.ImageIcon("/home/son/NetBeansProjects/Dictionary/images/save-file.png")); // NOI18N
        saveB.setText("Save");
        saveB.setBorderPainted(false);
        saveB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBMouseClicked(evt);
            }
        });
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        jButton1.setText("Voice");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchT, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(searchB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addB, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(editB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(removeB, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(248, 248, 248))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(367, 367, 367))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editB)
                            .addComponent(addB))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(removeB))
                            .addComponent(addPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchT, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void InitDictionary(){
        // Set add panel invisibility
        addPanel.setVisible(false);
//        removeTextF.setVisible(false);
        manage.insertFromFile();
    }
    
    private void searchTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTActionPerformed
            // TODO add your handling code here: 
        String wordS = searchT.getText();
        String explainW = manage.dictionaryLookup(wordS);
        explainT.setText(explainW);
    }//GEN-LAST:event_searchTActionPerformed

    private void searchBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBMouseClicked
        // TODO add your handling code here:
        String wordS = searchT.getText();
        String simW = manage.dictionarySearcher(wordS);
        String[] sims = simW.split("-_-");
        wordList.setListData(sims);
    }//GEN-LAST:event_searchBMouseClicked

    private void wordListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordListMouseClicked
        // TODO add your handling code here:
        String wget = wordList.getSelectedValue();
        explainT.setText(manage.dictionaryLookup(wget));
    }//GEN-LAST:event_wordListMouseClicked

    private void engTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engTextFieldActionPerformed

    private void addBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBMouseClicked
        // TODO add your handling code here:
        if(!addPanel.isVisible()){
            addPanel.setVisible(true);
            addB.setText("Add Word");
        }else{
            String engW = engTextField.getText();
            String vieW = vieTextField.getText();
            
//            System.out.println(manage.dictionaryLookup(engW));
            if(manage.dictionaryLookup(engW) != "Not find"){
                explainT.setText("Existed Word!!! \nPlease add new word!");
            }else{
                manage.addWord(engW, vieW);
                addPanel.setVisible(false);
                addB.setText("Add");
                explainT.setText("Add Successfully!!!");
                return;
            }
        }
        
    }//GEN-LAST:event_addBMouseClicked

    private void removeBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBMouseClicked
        // TODO add your handling code here:
        String removeW = JOptionPane.showInputDialog(null, "Remove Word!");
        while(removeW == null || removeW.length() == 0){
            if(removeW == null) return;
            else if(removeW.length() == 0){
                removeW = JOptionPane.showInputDialog(null, "You have to type something!");
            }
        }
        if(manage.dictionaryLookup(removeW) == "Not find"){
            JOptionPane.showMessageDialog(rootPane, "Cant find this word!");
            removeBMouseClicked(evt);
            return;
        }else{
            String rs = manage.removeWord(removeW);
            JOptionPane.showMessageDialog(rootPane, rs);
        }
    }//GEN-LAST:event_removeBMouseClicked

    private void vieTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vieTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vieTextFieldActionPerformed

    private void searchTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_searchTInputMethodTextChanged
        // TODO add your handling code here:
            
    }//GEN-LAST:event_searchTInputMethodTextChanged

    private void searchTKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTKeyReleased
        // TODO add your handling code here:
        String searchW = searchT.getText();
        String[] rs = manage.suggestSearch(searchW).split("-_-");
//        System.out.println(rs[0]);
        if(rs[0].isEmpty()){
            System.out.println(manage.fuzzySearch(searchW));
            
            rs = manage.suggestSearch(manage.fuzzySearch(searchW)).split("-_-");
            System.out.println(rs[0]);
        }
        wordList.setListData(rs);
    }//GEN-LAST:event_searchTKeyReleased

    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveBActionPerformed

    private void saveBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBMouseClicked
        // TODO add your handling code here:
        manage.dictionaryExportToFile();
        JOptionPane.showMessageDialog(rootPane, "Saved!!!");
        InitDictionary();
    }//GEN-LAST:event_saveBMouseClicked

    private void editBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBMouseClicked
        // TODO add your handling code here:
        String editW = JOptionPane.showInputDialog(null, "Edit Word:");
//        String[] sg = manage.suggestSearch(editW).split("-_-");
//        wordList.setListData(sg);
//        if(wordList.is)
        String explainW = JOptionPane.showInputDialog(null, "Type new meaning for this word:");
        int rs = manage.editWord(editW, explainW);
        if(rs == 1){
            JOptionPane.showMessageDialog(rootPane, "Edit successfully!!1");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Cant not find this word to edit!");
        }
    }//GEN-LAST:event_editBMouseClicked

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBActionPerformed

    private void editBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
         */
        DictionaryApplication apps = new DictionaryApplication();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DictionaryApplication().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JPanel addPanel;
    private javax.swing.JButton editB;
    private javax.swing.JTextField engTextField;
    private javax.swing.JTextArea explainT;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JPopupMenu jPopupMenu4;
    private javax.swing.JPopupMenu jPopupMenu5;
    private javax.swing.JPopupMenu jPopupMenu6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JButton removeB;
    private javax.swing.JButton saveB;
    private javax.swing.JButton searchB;
    private javax.swing.JTextField searchT;
    private javax.swing.JTextField vieTextField;
    private javax.swing.JList<String> wordList;
    // End of variables declaration//GEN-END:variables
}
